build:
  image: default-jammy
  environment:
    php:
      version: '8.2'
  dependencies:
    override:
      - composer update --prefer-dist --no-interaction
  nodes:
    analysis:
      tests:
        override:
          - command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-filter src --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
