@extends('laravelusers::modern.page')
@section('template_title', __('laravelusers::laravelusers.show-deleted-users'))
@section('users_content')
    <section class="lu-panel{{ \jeremykenedy\laravelusers\Support\Frontend::stylesheet() ? ' '.\jeremykenedy\laravelusers\Support\Frontend::classes('panel') : '' }}">
        <header class="lu-heading lu-card-heading"><h1 class="lu-list-title">@include('laravelusers::partials.icon', ['name' => 'delete']) {{ __('laravelusers::laravelusers.show-deleted-users') }}</h1><a class="lu-button lu-secondary" href="{{ route('users') }}">@include('laravelusers::partials.icon', ['name' => 'reply']) {{ __('laravelusers::ui.back') }}</a></header>
        @include('laravelusers::partials.bulk-actions', ['modern' => true, 'deleted' => true])
        <div class="lu-scroll{{ \jeremykenedy\laravelusers\Support\Frontend::stylesheet() ? ' '.\jeremykenedy\laravelusers\Support\Frontend::classes('scroll') : '' }}">
            <table data-lu-view="deleted" @if(\jeremykenedy\laravelusers\Support\Frontend::stylesheet()) class="{{ \jeremykenedy\laravelusers\Support\Frontend::classes('table') }}" @endif data-lu-table>
                <caption>{{ __('laravelusers::laravelusers.show-deleted-users') }}</caption>
                <thead><tr>@if(config('laravelusers.avatar.enabled', false) && (!config('laravelusers.bulkActions', false) || config('laravelusers.enabledDatatablesJs', false)))<th data-lu-no-sort><span class="lu-sr-only sr-only">{{ __('laravelusers::ui.avatar') }}</span></th>@endif
                            @if(config('laravelusers.bulkActions', false))@include('laravelusers::partials.select-all')@endif<th scope="col">{{ __('laravelusers::laravelusers.users-table.id') }}</th><th scope="col">{{ __('laravelusers::laravelusers.users-table.name') }}</th><th scope="col">{{ __('laravelusers::laravelusers.users-table.email') }}</th>@if(config('laravelusers.rolesEnabled'))<th scope="col">{{ __('laravelusers::laravelusers.users-table.role') }}</th>@endif
                            @if(config('laravelusers.activity.login', false) && config('laravelusers.showLastLoginColumn', false))<th scope="col">{{ __('laravelusers::ui.last_login_at') }}</th>@endif<th scope="col">{{ __('laravelusers::ui.deleted_at') }}</th>@if(config('laravelusers.activity.login', false) && config('laravelusers.showLastLoginDetailsColumn', false))<th>{{ __('laravelusers::ui.login_details') }}</th>@endif<th scope="col" data-lu-no-sort>{{ __('laravelusers::laravelusers.users-table.actions') }}</th></tr></thead>
                <tbody>
                    @forelse($users as $user)
                        <tr @include('laravelusers::partials.appearance-attributes', ['appearance' => $userAppearance[$user->getKey()] ?? null])>@if(config('laravelusers.avatar.enabled', false))<td>@include('laravelusers::partials.avatar', ['avatar' => $userAvatars[$user->getKey()]])</td>@endif
                            @if(config('laravelusers.bulkActions', false))<td data-lu-selection-cell>@include('laravelusers::partials.select-user')</td>@endif<td>{{ $user->id }}</td><td>{{ $user->name }}</td><td>@if(config('laravelusers.emailLinks', false))<a href="mailto:{{ $user->email }}" @if(config('laravelusers.tooltipsEnabled', true)) title="{{ __('laravelusers::ui.email_user') }}" @endif>{{ $user->email }}</a>@else{{ $user->email }}@endif</td>@if(config('laravelusers.rolesEnabled'))<td>{{ $user->roles->pluck('name')->implode(', ') }}</td>@endif
                            @if(config('laravelusers.activity.login', false) && config('laravelusers.showLastLoginColumn', false))<td>@include('laravelusers::partials.date', ['value' => $userActivity[$user->getKey()]['last_login_at'] ?? null, 'empty' => __('laravelusers::ui.no_logins')])</td>@endif<td>@include('laravelusers::partials.date', ['value' => $user->deleted_at])</td>@if(config('laravelusers.activity.login', false) && config('laravelusers.showLastLoginDetailsColumn', false))<td>@include('laravelusers::partials.login-details', ['details' => $userActivity[$user->getKey()] ?? []])</td>@endif<td><div class="lu-actions">
                            @if(\jeremykenedy\laravelusers\Support\UserAccess::allows('restore_users'))<form method="POST" action="{{ route('users.restore', $user->id) }}">@csrf<button type="submit" class="lu-button lu-success" aria-label="{{ __('laravelusers::ui.restore') }}" @if(config('laravelusers.tooltipsEnabled', true)) title="{{ __('laravelusers::ui.restore') }}" @endif>@include('laravelusers::partials.icon', ['name' => 'restore']) {{ __('laravelusers::ui.restore') }}</button></form>@endif
                            @if(\jeremykenedy\laravelusers\Support\UserAccess::allows('force_delete'))<form method="POST" action="{{ route('users.force-destroy', $user->id) }}" @if(config('laravelusers.confirmDelete', true)) data-lu-confirm="{{ __('laravelusers::ui.confirm_delete', ['name' => $user->name]) }}" @endif>@csrf @method('DELETE')<button type="submit" class="lu-button lu-danger" aria-label="{{ __('laravelusers::ui.permanently_delete') }}" @if(config('laravelusers.tooltipsEnabled', true)) title="{{ __('laravelusers::ui.permanently_delete') }}" @endif>@include('laravelusers::partials.icon', ['name' => 'delete']) {{ __('laravelusers::ui.permanently_delete') }}</button></form>@endif
                            @if(config('laravelusers.settings.enabled', false) && \jeremykenedy\laravelusers\Support\UserAccess::allows('edit_deleted'))<a class="lu-button" href="{{ route('users.deleted.edit', $user->id) }}" aria-label="{{ __('laravelusers::ui.edit') }}" @if(config('laravelusers.tooltipsEnabled', true)) title="{{ __('laravelusers::ui.edit') }}" @endif>@include('laravelusers::partials.icon', ['name' => 'edit']) <span>{{ __('laravelusers::ui.edit') }}</span></a>@endif
                            <x-laravelusers::email-actions :user="$user" :compact="true" :deleted="true" />
                        </div></td></tr>
                    @empty
                        <tr><td colspan="{{ 5 + (int) (config('laravelusers.activity.login', false) && config('laravelusers.showLastLoginColumn', false)) + (int) config('laravelusers.rolesEnabled') + (int) (config('laravelusers.activity.login', false) && config('laravelusers.showLastLoginDetailsColumn', false)) + (int) config('laravelusers.avatar.enabled', false) + (int) config('laravelusers.bulkActions', false) }}">{{ __('laravelusers::laravelusers.search.no-results') }}</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="lu-pagination">
            @if(config('laravelusers.showUserCount', false))<span>{{ __('laravelusers::ui.total_users', ['count' => $pagintaionEnabled ? $users->total() : $users->count()]) }}</span>@endif
            @if($pagintaionEnabled)<nav class="lu-actions" aria-label="{{ __('laravelusers::ui.pagination') }}">@if($users->previousPageUrl())<a class="lu-button lu-secondary" href="{{ $users->previousPageUrl() }}">{{ __('laravelusers::ui.previous') }}</a>@endif<span>{{ __('laravelusers::ui.page', ['page' => $users->currentPage(), 'total' => $users->lastPage()]) }}</span>@if($users->nextPageUrl())<a class="lu-button lu-secondary" href="{{ $users->nextPageUrl() }}">{{ __('laravelusers::ui.next') }}</a>@endif</nav>@endif
        </div>
    </section>
@endsection
