@if(\jeremykenedy\laravelusers\Support\UserAccess::allows('edit_account_access'))
@php($accountsAvailable = \jeremykenedy\laravelusers\Support\AccountPreferences::available(Auth::user()))
<section class="lu-package-settings" aria-labelledby="lu-account-settings-title"><h2 id="lu-account-settings-title" class="lu-title-heading"><span class="lu-title-icon lu-title-icon-avatar">@include('laravelusers::partials.icon', ['name' => 'user'])</span><span>{{ __('laravelusers::ui.account_access_title') }}</span></h2><p class="lu-muted text-muted">{{ __('laravelusers::ui.account_access_hint') }}</p>
@if(!$accountsAvailable)<p class="lu-alert" role="status">{{ __('laravelusers::ui.account_migration_required') }} <code>php artisan laravelusers:setup-accounts --migrate</code></p>@endif
<form method="POST" action="{{ route('users.settings.accounts') }}" id="lu-account-access-form">@csrf @method('PUT')<input type="hidden" name="apply_all" disabled><input type="hidden" name="confirmation" disabled><fieldset @if(!$accountsAvailable || !$settingsAvailable) disabled @endif><legend class="lu-sr-only sr-only">{{ __('laravelusers::ui.account_access_title') }}</legend><div class="lu-account-settings-grid">
@foreach(['enabled', 'settings_enabled'] as $setting)<div class="lu-settings-choice"><h3>{{ __('laravelusers::ui.account_'.$setting) }}</h3><p class="lu-muted text-muted">{{ __('laravelusers::ui.account_'.$setting.'_hint') }}</p><label class="lu-email-check"><input type="hidden" name="{{ $setting }}" value="0"><input type="checkbox" name="{{ $setting }}" value="1" @if(old($setting, config('laravelusers.account.'.$setting, false))) checked @endif> {{ __('laravelusers::ui.account_'.$setting) }}</label><button type="button" class="{{ $modern ? 'lu-button lu-secondary' : 'btn btn-light' }}" data-lu-account-apply="{{ $setting }}">@include('laravelusers::partials.icon', ['name' => 'users']) {{ __('laravelusers::ui.account_apply_all') }}</button></div>@endforeach
</div><div class="lu-settings-footer"><button class="{{ $modern ? 'lu-button' : 'btn btn-primary' }}" type="submit">@include('laravelusers::partials.icon', ['name' => 'save']) {{ __('laravelusers::ui.account_access_save') }}</button></div></fieldset></form></section>
<dialog id="lu-account-apply-dialog" class="lu-email-dialog" aria-labelledby="lu-account-apply-title"><header class="lu-email-heading"><h2 id="lu-account-apply-title">@include('laravelusers::partials.icon', ['name' => 'users']) {{ __('laravelusers::ui.account_apply_all') }}</h2><button class="lu-email-close" type="button" data-lu-apply-dismiss aria-label="{{ __('laravelusers::ui.close') }}">@include('laravelusers::partials.icon', ['name' => 'close'])</button></header><div class="lu-email-body"><p>{{ __('laravelusers::ui.account_apply_warning') }}</p><p data-lu-apply-summary></p><label for="lu-account-apply-confirmation">{{ __('laravelusers::ui.account_apply_confirmation') }}</label><input id="lu-account-apply-confirmation" class="lu-email-input" autocomplete="off" spellcheck="false"></div><footer class="lu-email-footer"><button class="lu-button lu-secondary" type="button" data-lu-apply-dismiss>{{ __('laravelusers::forms.cancel') }}</button><button class="lu-button" type="button" data-lu-apply-confirm disabled>{{ __('laravelusers::ui.account_apply_all') }}</button></footer></dialog>
@endif
